source "https://rubygems.org"

gem "rails", "~> 4"
gem "sqlite3"
gem "sass-rails"
gem "uglifier"
gem "coffee-rails"
gem "jquery-rails"
gem "bootstrap-sass"
gem "thin"
gem "pry"

group :test, :development do
  gem "rspec-rails"
  gem "factory_girl_rails"
  gem "capybara"
  gem "database_cleaner"
  gem "ruby_css_lint"
  gem "selenium-webdriver"
end
